/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cobacoba;

import static java.lang.String.valueOf;
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author Alif
 */
public class adddata extends javax.swing.JFrame {

    /**
     * Creates new form adddata
     */
    public adddata() {
        initComponents();
    }

    String nama ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnbcktomenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        reguler = new javax.swing.JRadioButton();
        ekonomi = new javax.swing.JRadioButton();
        eksklusif = new javax.swing.JRadioButton();
        estimasi = new javax.swing.JLabel();
        jarak1 = new javax.swing.JRadioButton();
        jarak2 = new javax.swing.JRadioButton();
        kategori = new javax.swing.JLabel();
        jarak = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        btnbcktomenu.setText("back to menu");
        btnbcktomenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbcktomenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TAMBAHKAN DATA");

        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });

        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel2.setText("Estimasi:");

        tes.setText("Nama Barang  :");

        jLabel4.setText("Kategori Pengiriman :");

        jLabel5.setText("Kategori jarak :");

        jLabel7.setText("Alamat Pengiriman  :");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        reguler.setText("Reguler");
        reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regulerActionPerformed(evt);
            }
        });

        ekonomi.setText("ekonomi");
        ekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekonomiActionPerformed(evt);
            }
        });

        eksklusif.setText("eksklusif");
        eksklusif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksklusifActionPerformed(evt);
            }
        });

        estimasi.setText("Day");

        jarak1.setText(">1000km");
        jarak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarak1ActionPerformed(evt);
            }
        });

        jarak2.setText(">10000km");
        jarak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarak2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd)
                            .addComponent(btnbcktomenu))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(eksklusif)
                        .addGap(18, 18, 18)
                        .addComponent(kategori)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estimasi))
                    .addComponent(jLabel4)
                    .addComponent(tes)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reguler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ekonomi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jarak1)
                                .addGap(18, 18, 18)
                                .addComponent(jarak2)
                                .addGap(31, 31, 31)
                                .addComponent(jarak))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnadd)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tes)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reguler)
                    .addComponent(ekonomi)
                    .addComponent(eksklusif)
                    .addComponent(kategori))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jarak1)
                    .addComponent(jarak2)
                    .addComponent(jarak))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(estimasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnbcktomenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbcktomenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbcktomenuActionPerformed
         Beranda menu = new Beranda();
        menu.show();
        
        dispose();
    }//GEN-LAST:event_btnbcktomenuActionPerformed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
//            nama = namaBarang.getText();
    }//GEN-LAST:event_namaBarangActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
         Beranda menu = new Beranda();
        menu.show();
        
        dispose();
        
        sqlTambahdata tambah = new sqlTambahdata();
        tambah.tambahData(namaBarang.getText(),kategori.getText(),jarak.getText(),estimasi.getText(),alamat.getText());
  
    }//GEN-LAST:event_btnaddActionPerformed

    private void ekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekonomiActionPerformed
        // TODO add your handling code here:
         ButtonGroup group = new ButtonGroup();
        group.add(reguler);
        group.add(eksklusif);
        group.add(ekonomi);
        estimasi.setText("ekonomi");
        kategori.setText("ekonomi");
        
    }//GEN-LAST:event_ekonomiActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_alamatActionPerformed

    private void regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regulerActionPerformed
         // TODO add your handling code here:
//         estimasi.setActionMap(am);

     
   ButtonGroup group = new ButtonGroup();
        group.add(reguler);
        group.add(eksklusif);
        group.add(ekonomi);
        
        estimasi.setText("reguler");
        kategori.setText("reguler");
    }//GEN-LAST:event_regulerActionPerformed

    private void eksklusifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksklusifActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(reguler);
        group.add(eksklusif);
        group.add(ekonomi);
        
        estimasi.setText("eksklusif");
        kategori.setText("eksklusif");
    }//GEN-LAST:event_eksklusifActionPerformed

    private void jarak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarak1ActionPerformed
        // TODO add your handling code here:
        ButtonGroup group = new ButtonGroup();
        group.add(jarak1);
        group.add(jarak2);
        jarak.setText(">1000km");
        if(estimasi.getText()=="eksklusif"){
            estimasi.setText("1 minggu");
        }
        if(estimasi.getText()=="ekonomi"){
            estimasi.setText("2 minggu");
        }
        if(estimasi.getText()=="reguler"){
            estimasi.setText("3 minggu");
        }   
    }//GEN-LAST:event_jarak1ActionPerformed

    private void jarak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarak2ActionPerformed
        // TODO add your handling code here:
           ButtonGroup group = new ButtonGroup();
        group.add(jarak1);
        group.add(jarak2);
       jarak.setText(">10000km");
        if(estimasi.getText()=="eksklusif"){
            estimasi.setText("3 minggu");
        }
        if(estimasi.getText()=="ekonomi"){
            estimasi.setText("4 minggu");
        }
        if(estimasi.getText()=="reguler"){
            estimasi.setText("5 minggu");
        }
    }//GEN-LAST:event_jarak2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddata().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbcktomenu;
    private javax.swing.JRadioButton ekonomi;
    public javax.swing.JRadioButton eksklusif;
    private javax.swing.JLabel estimasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jarak;
    private javax.swing.JRadioButton jarak1;
    private javax.swing.JRadioButton jarak2;
    private javax.swing.JLabel kategori;
    public javax.swing.JTextField namaBarang;
    private javax.swing.JRadioButton reguler;
    private javax.swing.JLabel tes;
    // End of variables declaration//GEN-END:variables


    
}
